DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password CHAR(60) NOT NULL,
created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE schedules (
id SERIAL PRIMARY KEY,
id_user INT NOT NULL,
day SMALLINT NOT NULL,
start_at TIME  NOT NULL,
end_at TIME NOT NULL,
created_at TIMESTAMPTZ DEFAULT now(),
CONSTRAINT fk_user
FOREIGN KEY (id_user) 
REFERENCES users(id) 
ON DELETE CASCADE
ON UPDATE CASCADE 
);
